name: deploy-development-to-lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Write pem files from secrets

      run: echo "Writing pem files from secrets" # Este comando no hará nada

    - name: Create ZIP deployment package
      run: zip -r deploy_package.zip ./

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_APP_REGION }}

    - name: Upload package to S3 bucket
      run: aws s3 cp deploy_package.zip "s3://${{ secrets.BUCKET_NAME }}/"
